"""
schema.py
Data contracts and models for Ceph Agent Knowledge Ingestion and Remediation Retrieval.
"""

from dataclasses import dataclass, field, asdict
from typing import List, Optional, Dict, Any


@dataclass
class KnowledgeChunk:
    """Represents a documentation chunk scraped across Ceph versions."""
    chunk_id: str
    ceph_release: str
    ceph_version: str
    title: str
    section_heading: str
    subsystem: str
    applicable_workflows: List[str]
    topic_intent: str
    summary: str
    key_concepts: List[str]
    health_codes_discussed: List[str]
    error_context: str
    source_url: str
    content: str
    commands_mentioned: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class HealthCheckEntry:
    """Represents a Ceph cluster health check definition."""
    code: str
    heading: str
    severity: str
    summary: str
    description: str
    resolution_commands: List[str]
    source_url: str
    ceph_version: str

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class CommandSpec:
    """Represents an agent CLI tool specification."""
    id: str
    command: str
    subsystem: str
    applicable_workflows: List[str]
    operational_intent: str
    resolves_errors_or_states: List[str]
    preconditions: str
    is_idempotent: bool
    danger_level: str  # 'read-only' | 'moderate' | 'destructive'
    canonical_example: str
    raw_syntax: str
    version_compat: str
    source: str

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class QueryContext:
    """Runtime context for remediation query."""
    stderr: str
    exit_code: int = 1
    workflow: Optional[str] = None
    target_destination: Optional[str] = None
    cluster_health: Optional[str] = None
    failed_command: Optional[str] = None
    additional_context: Optional[str] = None


@dataclass
class RemediationProposal:
    """Structured proposal generated by the LLM-based self-healing retrieval engine."""
    fix_command: str
    danger_level: str  # 'read-only' | 'moderate' | 'destructive'
    rationale: str
    doc_citation: str
    confidence: float
    applicable_workflow: str
    health_code: Optional[str] = None
    idempotent: bool = True
    suggested_retries: int = 1
    llm_reasoning: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
